version: '3'

services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
      args:
        REACT_APP_BACKEND_URL: /api
    container_name: fileshot-webui
    depends_on:
      - "postgresdb"
    environment:
      - DATABASE_HOST=postgresdb
      - DATABASE_NAME=strelka_ui
      - DATABASE_PASSWORD=postgres
      - DATABASE_USERNAME=postgres
      - STRELKA_HOST=strelka_frontend_1
    ports:
      - "8080:8080"

  postgresdb:
    image: docker.io/bitnami/postgresql:11
    environment:
      - POSTGRESQL_DATABASE=strelka_ui
      - POSTGRESQL_PASSWORD=postgres
      - POSTGRESQL_USERNAME=postgres
    ports:
      - "5432:5432"
    volumes:
      - data:/bitnami/postgresql

volumes:
  data:
