const APP_CONFIG = {
  BACKEND_URL: import.meta.env.VITE_BACKEND_URL || '/api',
  DEFAULT_EXCLUDED_SUBMITTERS: import.meta.env
    .VITE_DEFAULT_EXCLUDED_SUBMITTERS || ['SVCODSSTRELKA', 'Z00BNP7'],
  VIRUSTOTAL_API_KEY: import.meta.env.VITE_VIRUSTOTAL_API_KEY || '',
  API_TIMEOUT: 30000,
  LOGIN_TIMEOUT: 30000,
  SEARCH_URL: import.meta.env.VITE_SEARCH_URL,
  SEARCH_NAME: import.meta.env.VITE_SEARCH_NAME,
}

export { APP_CONFIG }
