# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: strelka.proto
# Protobuf Python Version: 5.29.0
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import runtime_version as _runtime_version
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
_runtime_version.ValidateProtobufRuntimeVersion(
    _runtime_version.Domain.PUBLIC,
    5,
    29,
    0,
    '',
    'strelka.proto'
)
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\rstrelka.proto\"I\n\x07Request\x12\n\n\x02id\x18\x01 \x01(\t\x12\x0e\n\x06\x63lient\x18\x02 \x01(\t\x12\x0e\n\x06source\x18\x03 \x01(\t\x12\x12\n\ngatekeeper\x18\x04 \x01(\x08\"|\n\nAttributes\x12\x10\n\x08\x66ilename\x18\x01 \x01(\t\x12+\n\x08metadata\x18\x02 \x03(\x0b\x32\x19.Attributes.MetadataEntry\x1a/\n\rMetadataEntry\x12\x0b\n\x03key\x18\x01 \x01(\t\x12\r\n\x05value\x18\x02 \x01(\t:\x02\x38\x01\"[\n\x0fScanFileRequest\x12\x0c\n\x04\x64\x61ta\x18\x01 \x01(\x0c\x12\x19\n\x07request\x18\x02 \x01(\x0b\x32\x08.Request\x12\x1f\n\nattributes\x18\x03 \x01(\x0b\x32\x0b.Attributes\")\n\x0cScanResponse\x12\n\n\x02id\x18\x01 \x01(\t\x12\r\n\x05\x65vent\x18\x02 \x01(\t2=\n\x08\x46rontend\x12\x31\n\x08ScanFile\x12\x10.ScanFileRequest\x1a\r.ScanResponse\"\x00(\x01\x30\x01\x62\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'strelka_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
  DESCRIPTOR._loaded_options = None
  _globals['_ATTRIBUTES_METADATAENTRY']._loaded_options = None
  _globals['_ATTRIBUTES_METADATAENTRY']._serialized_options = b'8\001'
  _globals['_REQUEST']._serialized_start=17
  _globals['_REQUEST']._serialized_end=90
  _globals['_ATTRIBUTES']._serialized_start=92
  _globals['_ATTRIBUTES']._serialized_end=216
  _globals['_ATTRIBUTES_METADATAENTRY']._serialized_start=169
  _globals['_ATTRIBUTES_METADATAENTRY']._serialized_end=216
  _globals['_SCANFILEREQUEST']._serialized_start=218
  _globals['_SCANFILEREQUEST']._serialized_end=309
  _globals['_SCANRESPONSE']._serialized_start=311
  _globals['_SCANRESPONSE']._serialized_end=352
  _globals['_FRONTEND']._serialized_start=354
  _globals['_FRONTEND']._serialized_end=415
# @@protoc_insertion_point(module_scope)
