"""add_s3_fields_for_resubmission

Revision ID: 1b23372700aa
Revises: 3671ee09c427
Create Date: 2025-08-04 16:20:29.846533

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '1b23372700aa'
down_revision = '3671ee09c427'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('file_submission', schema=None) as batch_op:
        batch_op.add_column(sa.Column('s3_key', sa.String(), nullable=True))
        batch_op.add_column(sa.Column('s3_expires_at', sa.DateTime(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('file_submission', schema=None) as batch_op:
        batch_op.drop_column('s3_expires_at')
        batch_op.drop_column('s3_key')
    # ### end Alembic commands ###
