"""file_submission_updates

Revision ID: 3671ee09c427
Revises: 75efd7e8b30a
Create Date: 2025-01-22 17:11:43.207910

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '3671ee09c427'
down_revision = '75efd7e8b30a'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('file_submission', schema=None) as batch_op:
         batch_op.add_column(sa.Column('highest_vt_count', sa.Integer(), nullable=True, server_default='-1'))
         batch_op.add_column(sa.Column('highest_vt_sha256', sa.String(), nullable=True))

    with op.batch_alter_table('file_submission', schema=None) as batch_op:
        op.execute('UPDATE file_submission fs set highest_vt_count = -1 where 1=1;')
        op.execute('''
        UPDATE file_submission fs
        SET 
            highest_vt_count = subquery.highest_vt,
            highest_vt_sha256 = subquery.highest_vt_sha256
        FROM (
            SELECT 
            id, 
            MAX(json->'enrichment'->>'virustotal')::integer AS highest_vt,
            MAX(json->'scan'->'hash'->>'sha256') AS highest_vt_sha256
            FROM (
            SELECT 
                id, 
                json_array_elements(
                (regexp_replace(strelka_response::text, '\\\\u0000', '', 'g'))::json
                ) AS json
            FROM file_submission
            ) x
            GROUP BY id
        ) subquery
        WHERE fs.id = subquery.id;
        ''')

    with op.batch_alter_table('file_submission', schema=None) as batch_op:
        # set the column to not nullable
        batch_op.create_index(batch_op.f('ix_file_submission_file_name'), ['file_name'], unique=False, )
        batch_op.create_index(batch_op.f('ix_file_submission_submitted_description'), ['submitted_description'], unique=False)

    # ### end Alembic commands ###


def downgrade():
    pass
    # ### commands auto generated by Alembic - please adjust! ###
    # keep everything as is and we fail forward
    # ### end Alembic commands ###
