"""init

Revision ID: 75efd7e8b30a
Revises: 
Create Date: 2025-01-22 17:04:58.724214

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '75efd7e8b30a'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('user',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_cn', sa.String(), nullable=True),
    sa.Column('first_name', sa.String(), nullable=True),
    sa.Column('last_name', sa.String(), nullable=True),
    sa.Column('last_login', sa.DateTime(), nullable=True),
    sa.Column('login_count', sa.Integer(), nullable=True),
    sa.Column('files_submitted', sa.Integer(), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('user_cn')
    )
    op.create_table('api_key',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('key', sa.String(), nullable=False),
    sa.Column('user_cn', sa.String(), nullable=False),
    sa.Column('expiration', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['user_cn'], ['user.user_cn'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('key')
    )
    op.create_table('file_submission',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('file_id', sa.String(), nullable=True),
    sa.Column('file_name', sa.String(), nullable=True),
    sa.Column('file_size', sa.Integer(), nullable=True),
    sa.Column('strelka_response', sa.JSON(), nullable=True),
    sa.Column('mime_types', sa.ARRAY(sa.String(), dimensions=1), nullable=True),
    sa.Column('yara_hits', sa.ARRAY(sa.String(), dimensions=1), nullable=True),
    sa.Column('files_seen', sa.Integer(), nullable=True),
    sa.Column('scanners_run', sa.ARRAY(sa.String(), dimensions=1), nullable=True),
    sa.Column('hashes', sa.ARRAY(sa.String(), dimensions=2), nullable=True),
    sa.Column('insights', sa.ARRAY(sa.String(), dimensions=1), nullable=True),
    sa.Column('iocs', sa.ARRAY(sa.String(), dimensions=1), nullable=True),
    sa.Column('submitted_type', sa.String(), nullable=True),
    sa.Column('submitted_from_ip', sa.String(), nullable=True),
    sa.Column('submitted_from_client', sa.String(), nullable=True),
    sa.Column('submitted_description', sa.String(), nullable=True),
    sa.Column('submitted_by_user_id', sa.Integer(), nullable=False),
    sa.Column('submitted_at', sa.DateTime(), nullable=True),
    sa.Column('processed_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['submitted_by_user_id'], ['user.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('file_id')
    )
    with op.batch_alter_table('file_submission', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_file_submission_submitted_at'), ['submitted_at'], unique=False)
        batch_op.create_index(batch_op.f('ix_file_submission_submitted_by_user_id'), ['submitted_by_user_id'], unique=False)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('file_submission', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_file_submission_submitted_by_user_id'))
        batch_op.drop_index(batch_op.f('ix_file_submission_submitted_at'))

    op.drop_table('file_submission')
    op.drop_table('api_key')
    op.drop_table('user')
    # ### end Alembic commands ###
